version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_teste
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${USER_LOGIN}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/sql/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql_data:
